# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-17 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('factory_name', models.CharField(max_length=30)),
                ('bar_code', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
