# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-18 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.FileField(null=True, upload_to='product.<built-in function id>'),
        ),
    ]
